deployment:
  tasks:
    - export DEPLOY_PATH=/home/c2499576c/repositories/cookpedia-backend 
    - export NODE_ENV=production
    - cd $DEPLOY_PATH
    - npm install
    - npm run build
    - pm2 restart all